In [3]:
from sklearn import datasets
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
iris = datasets.load_iris()
print(iris['data'][:5]) 
print(iris['target'][:5])
print( "X shape " + str( iris.data.shape))
print( "Y shape " + str( iris.target.shape))


# We can supply our own priors with 'priors' = 'array-like'(nclasses,)
# 'var_smoothing', portion of the largest variance of all features that is added to 
# variances for calculation stability
gnb = GaussianNB()


y_pred = gnb.fit(iris.data, iris.target).predict(iris.data)
print( (iris.target != y_pred).sum() / iris.data.shape[0])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]
X shape (150, 4)
Y shape (150,)
0.04


In [2]:
from sklearn import datasets
import pandas as pd
import numpy as np
from sklearn import svm
iris = datasets.load_iris()
print(iris['data'][:5]) 
print(iris['target'][:5])
print( "X shape " + str( iris.data.shape))
print( "Y shape " + str( iris.target.shape))

# SVC stands for support vector classifier
# LinearSVC = Linear Support Vector Machine for Regression
# SVR = Support Vector Machine for Rgression
# Where gamma determines the margins of separation
clf = svm.SVC(
    C = 1.0,    # Penalty parameter C of error term
    kernel = 'linear', # One of 'linear', 'poly',' rbf', 'sigmoid'
    degree = 3, # Degree of polynomial if poly is used
    gamma = 'scale', # coefficient for 'rbf', 'poly', and 'sigmoid'
    # default is 'auto' which used 1/n_features, scale uses 1/(n*X.var)
    coef0 = 0.0, # Independent term in kernel function 'poly' and 'sigmoid'
    shrinking = True, # shrinking heuristic
    probability = False, # enable probability estimates
    tol = 1e-3, # Tolerance for stopping criterion
    #cache_size, # Specify the size of the kernel cache
    #class_weight, # When not given, set to n_samples/(n_classes * np.bincount(y))
    max_iter = -1, # iterations with solver -1 = inf
    decision_function_shape = 'ovo', # 'ovo' one vs one, 'ovr' one vs rest,
    random_state = None # seed of sudo random number for probability estimates
)


clf.fit(iris.data, iris.target)
svm_pred = clf.predict(iris.data)
print( (iris.target != svm_pred).sum() / iris.data.shape[0])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]
X shape (150, 4)
Y shape (150,)
0.006666666666666667


In [3]:
from sklearn import tree

print(iris['data'][:5]) 
print(iris['target'][:5])
print( "X shape " + str( iris.data.shape))
print( "Y shape " + str( iris.target.shape))

clf = tree.DecisionTreeClassifier(
    criterion = 'entropy', # 'gini' for impurity and 'entropy' for information gain
    splitter = 'best', # 'best' split, 'random' best-random split
    max_depth = None, # max depth of the tree, if None then 
    # nodes expand until all leaves are pure or until all leaves have less
    # than min_samples_split
    min_samples_split = 2, # min number to split an internal node
    min_samples_leaf = 1, # min number of samples in a leaf node
    min_weight_fraction_leaf = 0, # minimum weighted fraction of sum of weights
    max_features = None, # number of features to look at for best split
    # usually max_features but can be sqrt(n_features) or log2(n_features)
    random_state = None, # seed used by random number generator
    max_leaf_nodes = None, # relative reduction in impurity, tries to limit leafs
    min_impurity_decrease = 0, # Split if equal or greater than this value
    class_weight = None, # weights in a dict{'class': value} for each class
    presort = False # for smaller datasets and restricted depth can speed up training, otherwise leave false
)



clf.fit(iris.data, iris.target)
tree_pred = clf.predict(iris.data)
print( (iris.target != tree_pred).sum() / iris.data.shape[0])
#tree.plot_tree(clf.fit(iris.data, iris.target))

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]
X shape (150, 4)
Y shape (150,)
0.0


In [4]:
from sklearn import datasets
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
X, y = datasets.load_iris(return_X_y = True)
iris = datasets.load_iris()
print(iris['data'][:5]) 
print(iris['target'][:5])
print( "X shape " + str( iris.data.shape))
print( "Y shape " + str( iris.target.shape))

clf = LogisticRegression(
    penalty = 'l2', # norm used, 'l1', 'elasticnet', 'none'
    dual = False, # dual or primal formulation, dual preferred when n_samples > n_features
    tol = 1e-4, # tolerance for stopping criteria
    C = 1.0, # inverse of regularization strength, small specify 
    fit_intercept = True, # Specifies if a constant should be added to the decision function
    class_weight = None, # weight specific classes, else all 1
    random_state = 0,  # generator to use when shuffling data
    solver = 'lbfgs', # 'newton-cg', 'lbfgs', 'sag', 'saga', 'liblinear'
    max_iter = 100, # Maximum number of iterations for solvers to converge
    multi_class = 'multinomial', # 'ovr' one vs rest, 'auto', 'multinomial'
    verbose = 0, # set verbose to any positive number for verbosity
    warm_start = False, # reuse the solution to previous call
    n_jobs = None, # Number of Cores to parallelize over with 'ovr'
    l1_ratio = None # only when penalty = 'elasticnet', 
).fit(X, y)
log_pred = clf.predict(X)
clf.score(X,y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]
X shape (150, 4)
Y shape (150,)


C:\Users\zjwar\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


0.9733333333333334

In [11]:
import plotly.graph_objects as go
import plotly.express as px
from plotly import subplots
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score, learning_curve, cross_val_predict

def plot_learning_curve(estimator, X, y, colnum, cv=None, n_jobs=1, train_sizes=np.linspace(.1, 1.0, 5),):
    train_sizes, train_scores, test_scores = learning_curve(
        estimator, X, y, cv=cv, n_jobs=n_jobs, train_sizes=train_sizes)
    train_scores_mean = np.mean(train_scores, axis=1)
    train_scores_std = np.std(train_scores, axis=1)
    test_scores_mean = np.mean(test_scores, axis=1)
    test_scores_std = np.std(test_scores, axis=1)
    
    if(colnum==1):
        leg=True
    else:
        leg=False
        
    p1 = go.Scatter(x=train_sizes, y=test_scores_mean + test_scores_std,
                    mode='lines',
                    line=dict(color="green", width=1),
                    showlegend=False,  )
    fig.append_trace(p1, 1, colnum)
    
    p2 = go.Scatter(x=train_sizes, y=test_scores_mean - test_scores_std,
                    mode='lines',
                    line=dict(color="green", width=1),
                    showlegend=False, fill='tonexty')
    fig.append_trace(p2, 1, colnum)
    
    p3 = go.Scatter(x=train_sizes, y=train_scores_mean + train_scores_std,
                    mode='lines',
                    line=dict(color="red", width=1),
                    showlegend=False)
    fig.append_trace(p3, 1, colnum)
    
    p4 = go.Scatter(x=train_sizes, y=train_scores_mean - train_scores_std,
                    mode='lines',
                    line=dict(color="red", width=1),
                    showlegend=False, fill='tonexty')
    fig.append_trace(p4, 1, colnum)
    
    p5 = go.Scatter(x=train_sizes, y=train_scores_mean, 
                    marker=dict(color='red'),
                    name="Training score", showlegend=leg)
    fig.append_trace(p5, 1, colnum)
    
    p6 = go.Scatter(x=train_sizes, y=test_scores_mean, 
                    marker=dict(color='green'),
                    name="Cross-validation score", showlegend=leg)
    fig.append_trace(p6, 1, colnum)
    fig.update_layout(
        title = go.layout.Title(
            text = 'Learning Curve'),
        xaxis = go.layout.XAxis(
            title = go.layout.xaxis.Title(
            text = "Number of training instances")),
        yaxis = go.layout.YAxis(
            title = go.layout.yaxis.Title(
            text = "Accuracy"))
        )

In [21]:
from sklearn import datasets
import pandas as pd
import numpy as np
from plotly.subplots import make_subplots
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_predict 

X, y = datasets.load_iris(return_X_y = True)
iris = datasets.load_iris()
knn_clf = KNeighborsClassifier(n_jobs=1)
y_train_pred = cross_val_predict(knn_clf, iris.data, iris.target, cv = 3, n_jobs=1)

fig = subplots.make_subplots(rows=1, cols=2,
  subplot_titles=("Learning Curves (Naive Bayes)",
  "Learning Curves (SVM, RBF kernel, gamma=0.001)"),
                            )
plot_learning_curve( knn_clf, iris.data, iris.target, 1, cv = 10, n_jobs =1)
plot_learning_curve( knn_clf, iris.data, iris.target, 2, cv = 10, n_jobs =1)
fig['layout'].update(hovermode='closest')
fig.show()
#py.iplot(fig)

In [9]:
from sklearn import datasets
import pandas as pd
import numpy as np
from plotly.subplots import make_subplots
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_predict, cross_val_score, StratifiedKFold

df1 = pd.read_csv('exp1a.csv')
df2 = pd.read_csv('exp1b.csv')
df3 = pd.read_csv('exp1c.csv')


for df in [df1, df2, df3]:
    data = df.drop('class', axis = 1)
    target = df['class']
    target.replace(-1, 0, inplace = True)

    for k in [1, 5, 11, 21]:
        clf = KNeighborsClassifier(
            n_neighbors = k, # number of neighbors
            #weights = 'distance', # weight function used in prediction
            n_jobs=1)
        cvals = cross_val_score(clf, data, target, cv = 10, scoring = 'accuracy')
        prediction = cross_val_predict(clf, data, target, cv = 10)
        print( np.mean(cvals))

0.9774999999999998
0.9525
0.9424999999999999
0.9275
0.96
0.9666666666666668
0.9466666666666667
0.9400000000000001
0.9409090909090908
0.9772727272727273
0.9454545454545455
0.9363636363636363
